complete -c pamac -l version -d "Show version"
complete -c pamac -s h -l help -d "Show help"

complete -c pamac -n '__fish_use_subcommand' -xa clean -d "Clean cache or build files"
complete -c pamac -n 'contains clean (commandline -poc)' -x -s k -l keep -d "Specify how many versions of each package are kept in the cache directory"
complete -c pamac -n 'contains clean (commandline -poc)' -x -s u -l uninstalled -d "Only target uninstalled packages"
complete -c pamac -n 'contains clean (commandline -poc)' -x -s b -l build-files -d "Remove all build files"
complete -c pamac -n 'contains clean (commandline -poc)' -x -s d -l dry-run -d "Do not remove files, only find candidate packages"
complete -c pamac -n 'contains clean (commandline -poc)' -x -s v -l verbose -d "Display all file names"
complete -c pamac -n 'contains clean (commandline -poc)' -x -l no-confirm -d "Bypass any confirmation messages"

complete -c pamac -n '__fish_use_subcommand' -xa checkupdates -d "Safely check updates without modifying databases"
complete -c pamac -n 'contains checkupdates (commandline -poc)' -x -s a -l aur -d "Also check updates in AUR"
complete -c pamac -n 'contains checkupdates (commandline -poc)' -x -l devel -d "Also check development updates (use with --aur)"
complete -c pamac -n 'contains checkupdates (commandline -poc)' -x -s q -l quiet -d "Only change one line per update"
complete -c pamac -n 'contains checkupdates (commandline -poc)' -x -l builddir -d "Build directory (use with --devel)"

complete -c pamac -n '__fish_use_subcommand' -xa update -d "Upgrade your system"
complete -c pamac -n 'contains update (commandline -poc)' -x -s a -l aur -d "Also upgrade from AUR"
complete -c pamac -n 'contains update (commandline -poc)' -x -l devel -d "Also upgrade development packages (use with --aur)"
complete -c pamac -n 'contains update (commandline -poc)' -x -l builddir -d "Build directory (use with --aur)"
complete -c pamac -n 'contains update (commandline -poc)' -x -l force-refresh -d "Force refresh of databases"
complete -c pamac -n 'contains update (commandline -poc)' -x -l enable-downgrade -d "Enable package downgrades"
complete -c pamac -n 'contains update (commandline -poc)' -x -l ignore -d "Ignore a package(s) upgrade"
complete -c pamac -n 'contains update (commandline -poc)' -x -l overwrite -d "Overwrite conflicting files"
complete -c pamac -n 'contains update (commandline -poc)' -x -l no-confirm -d "Bypass confirmation messages"
complete -c pamac -n '__fish_use_subcommand' -xa upgrade -d "Upgrade your system"
complete -c pamac -n 'contains upgrade (commandline -poc)' -x -s a -l aur -d "Also upgrade from AUR"
complete -c pamac -n 'contains upgrade (commandline -poc)' -x -l devel -d "Also upgrade development packages (use with --aur)"
complete -c pamac -n 'contains upgrade (commandline -poc)' -x -l builddir -d "Build directory (use with --aur)"
complete -c pamac -n 'contains upgrade (commandline -poc)' -x -l force-refresh -d "Force refresh of databases"
complete -c pamac -n 'contains upgrade (commandline -poc)' -x -l enable-downgrade -d "Enable package downgrades"
complete -c pamac -n 'contains upgrade (commandline -poc)' -x -l ignore -d "Ignore a package(s) upgrade"
complete -c pamac -n 'contains upgrade (commandline -poc)' -x -l overwrite -d "Overwrite conflicting files"
complete -c pamac -n 'contains upgrade (commandline -poc)' -x -l no-confirm -d "Bypass confirmation messages"

complete -c pamac -n '__fish_use_subcommand' -xa search -d "Search for packages or files"
complete -c pamac -n 'contains search (commandline -poc)' -x -s a -l aur -d "Also search in AUR"
complete -c pamac -n 'contains search (commandline -poc)' -x -s f -l files -d "Search for packages which own given filenames"

complete -c pamac -n '__fish_use_subcommand' -xa info -d "Display package details"
complete -c pamac -n 'contains info (commandline -poc)' -x -s a -l aur -d "Also search in AUR"

complete -c pamac -n '__fish_use_subcommand' -xa list -d "List packages, groups, repositories or files"
complete -c pamac -n 'contains list (commandline -poc)' -x -s i -l installed -d "List installed packages"
complete -c pamac -n 'contains list (commandline -poc)' -x -s o -l orphans -d "List packages that are no longer required by any installed package"
complete -c pamac -n 'contains list (commandline -poc)' -x -s m -l foreign -d "List packages that were not found in repositories"
complete -c pamac -n 'contains list (commandline -poc)' -x -s g -l groups -d "List all packages that are members of give groups, or list all groups"
complete -c pamac -n 'contains list (commandline -poc)' -x -s r -l repos -d "List all packages available in given repos, or list all repos"
complete -c pamac -n 'contains list (commandline -poc)' -x -s f -l files -d "List files owned by given packages"

complete -c pamac -n '__fish_use_subcommand' -xa install -d "Install packages"
complete -c pamac -n 'contains install (commandline -poc)' -x -l ignore -d "Ignore a package upgrade"
complete -c pamac -n 'contains install (commandline -poc)' -x -l overwrite -d "Overwrite conflicting files"
complete -c pamac -n 'contains install (commandline -poc)' -x -l no-confirm -d "Bypass confirmation messages"

complete -c pamac -n '__fish_use_subcommand' -xa reinstall -d "Reinstall packages"
complete -c pamac -n 'contains reinstall (commandline -poc)' -x -l overwrite -d "Overwrite conflicting files"
complete -c pamac -n 'contains reinstall (commandline -poc)' -x -l no-confirm -d "Bypass confirmation messages"

complete -c pamac -n '__fish_use_subcommand' -xa clone -d "Clone or sync packages' build files from AUR"
complete -c pamac -n 'contains clone (commandline -poc)' -x -l builddir -d "Build directory"
complete -c pamac -n 'contains clone (commandline -poc)' -x -s r -l recurse -d "Also clone needed dependencies"
complete -c pamac -n 'contains clone (commandline -poc)' -x -l overwrite -d "Overwrite existing files"

complete -c pamac -n '__fish_use_subcommand' -xa build -d "Build packages from AUR"
complete -c pamac -n 'contains build (commandline -poc)' -x -l builddir -d "Build directory"
complete -c pamac -n 'contains build (commandline -poc)' -x -l no-clone -d "Don't clone build files from AUR, use only local files"
complete -c pamac -n 'contains build (commandline -poc)' -x -l no-confirm -d "Bypass confirmation messages"

complete -c pamac -n '__fish_use_subcommand' -xa remove -d "Remove packages"
complete -c pamac -n 'contains remove (commandline -poc)' -x -s o -l orphans -d "Remove dependencies that are not required by other packages"
complete -c pamac -n 'contains remove (commandline -poc)' -x -l no-confirm -d "Bypass confirmation messages"
