set -l foreground 546e7a
set -l selection  80cbc4
set -l comment    aabfc9

set -l red      ff5370
set -l pink     f07178
set -l orange   f78c6c
set -l yellow   ffcb6b
set -l green    c3e88d
set -l paleblue b2ccd6
set -l cyan     89ddff
set -l blue     82aaff
set -l purple   c792ea
set -l violet   bb80b3
set -l brown    ab7967

set -l links      39ADB5
set -l functions  6182B8
set -l keywords   7C4DFF
set -l tags       E53935
set -l strings    91B859
set -l operators  39ADB5
set -l attributes F6A434
set -l numbers    F76D47
set -l parameters F76D47
set -l comments   AABFC9

set -g fish_color_autosuggestion $selection
set -g fish_color_command        $functions
set -g fish_color_comment        $comments
set -g fish_color_end            $orange
set -g fish_color_error          $red
set -g fish_color_escape         $pink
set -g fish_color_normal         $foreground
set -g fish_color_operator       $operators
set -g fish_color_param          $parameters
set -g fish_color_quote          $strings
set -g fish_color_redirection    $foreground
set -g fish_color_search_match   --background=$selection
set -g fish_color_selection      --background=$selection
set -g fish_color_cwd            $links
